<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1689132168048' stop='1689132170261'>
    <name>Faker:</name>
    <title>Faker:</title>
    <test-cases>
        <test-case start='1689132169176' status='failed' stop='1689132169881'>
            <name>FakerDemo</name>
            <title>FakerDemo</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='codeceptjs'/>
            </labels>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Main session - Last Seen Screenshot' source='e4d251cd-74a5-40f0-97a7-1f4beafe03cf-attachment.png' type='image/png' size='6897'/>
            </attachments>
            <failure>
                <message>faker1.name.findName is not a function</message>
                <stack-trace>TypeError: faker1.name.findName is not a function
                    at Test.&lt;anonymous> (C:\POC\tests\faker.js:17:34)
                    at test.fn (C:\POC\node_modules\codeceptjs\lib\scenario.js:92:14)
                    at callFnAsync (C:\POC\node_modules\mocha\lib\runnable.js:394:21)
                    at Runnable.run (C:\POC\node_modules\mocha\lib\runnable.js:338:7)
                    at Runner.runTest (C:\POC\node_modules\mocha\lib\runner.js:666:10)
                    at C:\POC\node_modules\mocha\lib\runner.js:789:12
                    at next (C:\POC\node_modules\mocha\lib\runner.js:581:14)
                    at C:\POC\node_modules\mocha\lib\runner.js:591:7
                    at next (C:\POC\node_modules\mocha\lib\runner.js:474:14)
                    at cbHookRun (C:\POC\node_modules\mocha\lib\runner.js:539:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>